#! /usr/bin/env zsh

# Description:
#   A script to view all the images, containers, and networks present
#   on the host

# View running containers
echo ""
echo "Running containers:"
echo ""

if [[ "`docker ps -aq | wc -l`" -eq 0 ]]
then
  echo ""
  echo "  ** No running containers **"
  echo ""
else
  docker ps --all
  
  echo ""
fi


# View images
echo ""
echo "Local images:"
echo ""

if [[ "`docker images -q | wc -l`" -eq 0 ]]
then
  echo ""
  echo "  ** No docker images **"
  echo ""
else
  docker images --all

  echo ""
fi


# View newtorks
echo ""
echo "Networks:"
echo ""

if [[ "`docker network ls -q | wc -l`" -eq 0 ]]
then
  echo ""
  echo "  ** No docker networks **"
  echo ""
else
  docker network ls

  echo ""
fi


# View volumes
echo ""
echo "Volumes:"
echo ""

if [[ "`docker volume ls -q | wc -l`" -eq 0 ]]
then
  echo ""
  echo "  ** No docker volumes **"
  echo ""
else
  docker volume ls

  echo ""
fi
