#! /usr/bin/env zsh

# Description:
#   This script is used to generate a new laravel project.
#   It uses composer on docker to create a new laravel project,
#   and adds homestead to it.
#   A git repository is initialised in the project directory.
#
#
# Exit values:
#   0 : Success
#   1 : Wrong argument count
#   2 : Bad project-name format
#   3 : Project directory already exists


. `dirname ${0}`/src/includes/functions/assert_argument_count.zsh


assert_argument_count equal 1 ${#} "Usage: `basename ${0}` project-name."


# variables
SSH_KEY_NAME="homestead-id_rsa"


# Validate the project-name
# Format: PascalCase alphanumeric
if [[ "${1:0:1}" =~ [0-9] ]] \    # the name cannot start with a number
|| ! [[ "${1:0:1}" =~ [A-Z] ]] \  # the name must start with an uppercase character
|| [[ "${1}" =~ [^a-zA-Z0-9] ]]   # allowed characters in the project name
then
  echo ""
  echo "Bad project-name format."
  echo "PascalCase alphanumeric string expected. The string cannot start with a number."
  echo ""

  exit 2
fi


# Check if the project exists
if [ -d ${1} ]
then
  echo ""
  echo "The project directory \"${1}\" already exists"
  echo "Exiting..."
  echo ""

  exit 3
fi


# Pull a fresh laravel project through composer on docker
echo ""
echo "Creating a fresh laravel application"
echo ""

docker run \
  --rm \
  --interactive \
  --tty \
  --volume ${PWD}:/app \
  --user `id -u`:`id -g` \
  composer \
    composer create-project --prefer-dist laravel/laravel ${1}


# Go into the project directory
cd ${1}


# Post-installation tasks
echo ""
echo "Performing the following post-installation tasks:"
echo "  * add homestead to the laravel project"
echo "  * generate Vagrantfile and Homestead.yaml file"
echo "  * set the application namespace to: ${1}"
echo "  * update Homestead.yaml to match the host machine parameters"
echo "  * update the application name"
echo "  * update the application url"
echo "  * set the application's mail sender's name and address"
echo ""

docker run \
  --rm \
  --interactive \
  --tty \
  --volume ${PWD}:/app \
  --user `id -u`:`id -g` \
  composer \
    composer require laravel/homestead --dev

docker run \
  --rm \
  --interactive \
  --tty \
  --volume ${PWD}:/app \
  --user `id -u`:`id -g` \
  composer \
    php vendor/bin/homestead make

docker run \
  --rm \
  --interactive \
  --tty \
  --volume ${PWD}:/app \
  --user `id -u`:`id -g` \
  composer \
    php artisan app:name ${1}

# Set the ssh key to be able to connect to vagrant
sed -i "s/id_rsa/${SSH_KEY_NAME}/g" Homestead.yaml

# Update the file mapping to homestead
sed -i "s%/app%${PWD}%" Homestead.yaml

# Update the name and the hostname of the homestead machine
sed -i "s/app/`echo ${1} | tr '[:upper:]' '[:lower:]'`/g" Homestead.yaml

# Update the application name and url
sed -i \
  -e "s/`grep APP_NAME .env`/APP_NAME=${1}/" \
  -e "s%`grep APP_URL .env`%APP_URL=http://homestead.test%" \
  .env

# Set an application timezone environment variable, and set it to indian/mauritius
sed -i "s%'UTC'%env('APP_TIMEZONE', 'UTC')%" config/app.php
sed -i "$(( $(grep -n '^APP_*' .env | tail -n 1 | cut -f 1 -d ':') + 1))iAPP_TIMEZONE=Indian/Mauritius" .env

# Set the application mail-sender's name line
sed -i "$(( $(grep -n '^MAIL_*' .env | tail -n 1 | cut -f 1 -d ':') + 1))iMAIL_FROM_NAME=" .env

# Set the application mail-sender's address line
sed -i "$(( $(grep -n '^MAIL_*' .env | tail -n 1 | cut -f 1 -d ':') + 1))iMAIL_FROM_ADDRESS=" .env



# Set-up git
echo ""
echo "Setting up Git version control for the project"
echo ""

git init
git add .
git commit -m 'initial commit'
git checkout -b 'development'


# Done!
echo ""
echo "The project ${1} has successfully been created."
echo ""
echo ""
