#! /usr/bin/env zsh

##
# Description:
#   A script to restore the contents of pass from a cleartext
#   password file which was generated using pass-backup
##


if [[ ${#} -ne 1 ]]
then
  echo "ERROR: 1 argument expected; ${#} provided"

  echo "Usage: `basename ${0}` PATH_TO_EXPORTED_PASSWORD_FILE"

  echo 1
fi



# Check password file existence
if [[ ! -f ${1} ]]
then
  echo ""
  echo "The password file \"${1}\" does not exist."
  echo "Exiting..."
  echo ""

  exit 2
fi


# Insert the passwords
cat ${1} | while read password_line
do
  local username=`echo ${password_line} | cut -d ' ' -f 1`
  local password=`echo ${password_line} | cut -d ' ' -f 2`

  echo "${password}\n${password}" | pass insert ${username}
done


echo ""
echo "Passwords successfully restored!"
echo ""
