#! /usr/bin/env zsh

##
# Description:
#   A script to export all the passwords present in pass
#   to a file in cleartext
##


if [[ ${#} -ne 1 ]]
then
  echo "ERROR: 1 argument expected; ${#} provided."

  echo "Usage: `basename ${0}` PATH_TO_DESTINATION_DIRECTORY"

  exit 1
fi


# Variables
password_store_path="${HOME}/.password-store/"
filetype=".gpg"
output_filename="password-file"


# Check if path provided is valid
if [ ! -d ${1} ]
then
  echo ""
  echo "The path provided is not valid"
  echo "Exiting..."
  echo ""

  exit 2
else
  output_filepath="${1}/${output_filename}"
fi


# Check output file existence
if [ -f "${output_filepath}" ]
then
  echo ""
  echo "The output file \"${output_filename}\" already exists."
  echo "Remove it, and re-run the backup script."
  echo "Exiting..."
  echo ""

  exit 3
fi


# Create output file
touch ${output_filepath}


# Fill the output file
for password_path in `find ${password_store_path} -name "*${filetype}"`
do
  # remove the prefix and suffix of the path
  password_path=${${password_path%${filetype}}#${password_store_path}}

  echo "${password_path} `pass ${password_path}`" >> ${output_filepath}
done


echo ""
echo "Passwords successfully backed up!"
echo ""
