#! /usr/bin/env python3


import argparse
from subprocess import run

from modules.Print import Print


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="A script to update the system.")

    parser.add_argument("--refresh", action="store_true", help="Refresh the pacman mirrors.")

    arguments = parser.parse_args()

    if arguments.refresh:
        Print.info("Refreshing the pacman mirrors.")
        Print.eol(2)

        run(["sudo", "pacman-mirrors", "-f"])

        Print.eol(2)
        Print.success("Refreshed the pacman mirrors.")
        Print.eol(2)


    Print.info("Upgrading pacman's packages.")
    Print.eol(2)

    run(["sudo", "pacman", "-Syyu"])

    Print.eol(2)
    Print.success("Upgraded pacman's packages.")
    Print.eol(2)


    Print.info("Upgrading AUR's packages.")
    Print.eol(2)

    run(["yaourt", "-Syuua"])

    Print.eol(2)
    Print.success("Upgraded AUR's packages.")
    Print.eol(2)
